{% set version = "0.0.9" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-xml2r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/XML2R_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/XML2R/XML2R_{{ version }}.tar.gz
  sha256: 3b8ed1361d57ce3714b827d52636e4f428c3d7f817e6ba5be970d0180f830160

build:
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-httr
    - r-plyr
    - r-xml
  run:
    - r-base
    - r-httr
    - r-plyr
    - r-xml

test:
  commands:
    - $R -e "library('XML2R')"           # [not win]
    - "\"%R%\" -e \"library('XML2R')\""  # [win]

about:
  home: https://github.com/cpsievert/XML2R
  license: GPL-2.0-or-later
  summary: XML2R is a framework that reduces the effort required to transform XML content into number of tables while preserving parent to child relationships.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
