{% set version = "0.0.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-xml2r
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/XML2R_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/XML2R/XML2R_{{ version }}.tar.gz
  sha256: bff23b583d00a04c1dd7a58830b43c9a8468a754cc23b5e68cd410bb8aef5aef

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcurl
    - r-xml
    - r-plyr
  run:
    - r-base
    - r-rcurl
    - r-xml
    - r-plyr

test:
  commands:
    - $R -e "library('XML2R')"           # [not win]
    - "\"%R%\" -e \"library('XML2R')\""  # [win]

about:
  home: http://cpsievert.github.com/XML2R
  license: GPL-2.0-or-later
  summary: XML2R is a framework that reduces the effort required to transform XML content into number of tables while preserving parent to child relationships.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: XML2R
# Title: EasieR XML data collection
# Version: 0.0.6
# Author: Carson Sievert <sievert@iastate.edu>
# Maintainer: Carson Sievert <sievert@iastate.edu>
# Description: XML2R is a framework that reduces the effort required to transform XML content into number of tables while preserving parent to child relationships.
# License: GPL (>= 2)
# Depends: R (>= 2.15.1), XML
# Imports: RCurl, plyr
# Date: 2014-03-09
# URL: http://cpsievert.github.com/XML2R
# BugReports: http://github.com/cpsievert/XML2R/issues
# Packaged: 2014-03-09 21:06:15 UTC; cpsievert
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-03-10 00:29:38
